#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive

installpkg(){
    dpkg-query --status $1 >/dev/null || apt-get install -y $1
}

apt-get update
installpkg php5
installpkg php5-mysql
installpkg redis-server
installpkg mysql-server
installpkg apache2-utils
installpkg apache2-suexec-custom

echo "ServerName localhost" > /etc/apache2/conf-enabled/servername.conf
a2enmod suexec
a2enmod rewrite
a2dissite 000-default.conf
cp /tmp/001-default.conf /etc/apache2/sites-available
a2ensite  001-default.conf
service apache2 restart

